name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run fmt
        run: |
          type cargo
          cargo fmt --all --check
      - name: Run test
        run: |
          cargo install --locked cargo-pgrx
          cargo pgrx init
          cargo pgrx test
