name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Cache pgrx build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            /home/runner/.pgrx
          key: ${{ runner.os }}-cargo-pgrx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-pgrx-
      - name: Install cargo-pgrx if missing
        run: |
          if ! command -v cargo-pgrx &> /dev/null; then
            sudo apt-get update && sudo apt-get install libreadline-dev -y
            cargo install cargo-pgrx --locked
            cargo pgrx init
          fi
      - name: Run fmt
        run: |
          type cargo
          cargo fmt --all --check
      - name: Run tests
        run: cargo pgrx test
