name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: setup
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run fmt
        run: |
          type cargo
          cargo fmt --all --check
      - name: Run test
        run: |
          cargo install --locked cargo-pgrx
          cargo pgrx init
          cargo pgrx test
